vibeblast:
    Item_Information:
        Item_Name: "&1V&9i&3b&be &1B&9l&3a&bst"
        Item_Type: 417
    Shooting:
        Cancel_Left_Click_Block_Damage: true
        Cancel_Right_Click_Interactions: true
        Projectile_Amount: 1
        Projectile_Type: energy
        Projectile_Subtype: 40-1-NONE-0
        Projectile_Damage: 10
        Delay_Between_Shots: 10
    Reload:
        Enable: false
    Hit_Events:
        Enable: true
